Merged various fixes for embedded mcpp:
- Skip BOM in UTF-8 encoded file.
- Fixed initialization of sh_file and sh_line.
- Fixed bug where lines with inline comments were removed.
- Fixed "discards 'const' qualifier" compiler warnings.
- Fixed error C4703 on VS2019 build.
- Some other suggested fixes from SourceForge discussions.

Removed old script editor compatibility from parser (unnecessary).